import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class FrontendContractTests(unittest.TestCase):
    def test_timeline_controls_and_curve_link_are_wired(self):
        html = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
        javascript = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="flightTimeline"', html)
        self.assertIn('id="vehicleWarning"', html)
        self.assertIn('id="serviceStopped"', html)
        self.assertIn('id="exitProgramButton"', html)
        self.assertIn('role="alert"', html)
        self.assertIn('role="alert"', html)
        self.assertIn('data-timeline-scope="important"', html)
        self.assertIn('id="timelineCategory"', html)
        self.assertIn("function renderTimeline(", javascript)
        self.assertIn('fetch("/api/health"', javascript)
        self.assertIn('fetch("/api/browser-open"', javascript)
        self.assertIn('"/api/browser-close"', javascript)
        self.assertIn('fetch("/api/shutdown"', javascript)
        self.assertIn('"X-PX4-Health-Client": "browser"', javascript)
        self.assertIn("navigator.sendBeacon(", javascript)
        self.assertIn('serviceStopped?.classList.remove("hidden")', javascript)
        self.assertIn("data.meta.vehicle_compatibility_warning", javascript)
        self.assertIn("function jumpToTimelineTime(", javascript)
        self.assertIn("function addTimelineFields(", javascript)
        self.assertIn("resolveTimelineField", javascript)
        self.assertIn("function importantTimelineItems(", javascript)
        self.assertIn("function groupTimelineItems(", javascript)
        self.assertIn("function handleMetricChartAction(", javascript)
        self.assertIn('data-toggle-chart-timeline', javascript)
        self.assertIn('class="chart-timeline-layer hidden"', javascript)
        self.assertIn('aria-pressed="false"', javascript)
        self.assertIn("timelineVisible: false", javascript)
        self.assertIn('data-toggle-plot-timeline=', javascript)
        self.assertIn("function drawCanvasTimeline(", javascript)
        self.assertIn("function nearestTimelineGroup(", javascript)
        self.assertIn('class="plot-event-readout ${severity}"', javascript)
        self.assertIn('readout.classList.toggle("timeline-active", plot.timelineVisible)', javascript)
        self.assertIn('class="plot-event-readout empty"', javascript)
        self.assertIn('class="plot-event-header"', javascript)
        self.assertIn('class="plot-event-row" role="listitem"', javascript)
        self.assertIn('class="plot-event-severity ${escapeHtml(itemSeverity)}"', javascript)
        self.assertIn('class="plot-event-category"', javascript)
        self.assertIn('class="plot-event-title"', javascript)
        self.assertIn('class="plot-event-list" role="list"', javascript)
        self.assertIn("pinnedTimelineItems: null", javascript)
        self.assertIn("function canvasTimelineGroupAt(", javascript)
        self.assertIn("function pinCanvasTimelineGroup(", javascript)
        self.assertIn('data-clear-pinned-event=', javascript)
        self.assertIn('class="plot-event-pinned"', javascript)
        self.assertIn("plot.pinnedTimelineItems = group.items.slice()", javascript)
        self.assertIn("function enumFieldHelp(", javascript)
        self.assertIn("function curveFieldHelp(", javascript)
        self.assertIn('${curveFieldHelp(field.name, field)}', javascript)
        self.assertIn('${curveFieldHelp(field.key, field)}', javascript)
        self.assertIn('class="field-help-badge"', javascript)
        self.assertIn('title="${escapeHtml(nativeHint)}"', javascript)
        self.assertIn('self.send_header("Cache-Control", "no-store, max-age=0")', (ROOT / "app.py").read_text(encoding="utf-8"))
        self.assertIn("field.enum_title", javascript)
        self.assertIn("field.enum_note", javascript)
        self.assertIn("function decodeCurveValue(", javascript)
        self.assertIn('line.enumKind === "bitmask"', javascript)
        self.assertIn('line.enumKind === "annotation"', javascript)
        self.assertIn('"magnetometer": ["未见明显异常"', javascript)
        self.assertNotIn('class="experimental-badge"', javascript)
        self.assertIn('class="evidence-value-wrap"', javascript)
        self.assertIn('data-full-value="${escapeHtml(fullValue)}"', javascript)
        self.assertIn('"磁场模长中位数"', javascript)
        self.assertIn("B = √(X² + Y² + Z²)", javascript)
        self.assertIn("vehicle_magnetometer.magnetometer_ga[0..2]", javascript)
        self.assertIn('"磁力计创新检验比 P95"', javascript)
        self.assertIn('"高低负载磁场模长差"', javascript)
        self.assertIn('"磁场-负载秩相关系数 ρ"', javascript)
        self.assertIn("evidenceLabelHelp[label]", javascript)
        self.assertIn("function showEvidenceTooltip(", javascript)
        self.assertIn('tooltip.id = "evidenceFloatingTooltip"', javascript)
        self.assertIn("const fullValue = item.full_value || item.value", javascript)
        self.assertIn("function updateAnomalyWindowControls(", javascript)
        self.assertIn("function toggleAnomalyWindows(", javascript)
        self.assertIn('data-anomaly-more', javascript)
        styles = (ROOT / "static" / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".evidence-value {", styles)
        self.assertIn(".service-stopped {", styles)
        self.assertIn(".exit-program-button {", styles)
        self.assertIn(".vehicle-warning {", styles)
        self.assertIn(".evidence { box-sizing: border-box; min-width: 0", styles)
        self.assertIn(".evidence-floating-tooltip.visible", styles)
        self.assertIn(".anomaly-window-hidden { display: none; }", styles)
        self.assertIn(".anomaly-more {", styles)
        self.assertIn(".explorer-legend .enum-tooltip { display: block", styles)
        self.assertIn(".explorer-legend .enum-grid { display: grid", styles)
        self.assertIn(".field-help-badge {", styles)
        self.assertIn(".field-option .enum-tooltip { display: none", styles)
        self.assertIn(".timeline-toggle {", styles)
        self.assertIn(".timeline-toggle.active {", styles)
        self.assertIn(".chart-timeline-marker.severe line", styles)
        self.assertIn(".explorer-plot-actions {", styles)
        self.assertIn(".plot-event-readout {", styles)
        self.assertIn(".plot-readout.timeline-active {", styles)
        self.assertIn(".plot-event-header {", styles)
        self.assertIn(".plot-event-list {", styles)
        self.assertIn("overflow-y: auto", styles)
        self.assertIn(".plot-event-row {", styles)
        self.assertIn("height: 96px", styles)
        self.assertIn(".plot-event-controls {", styles)
        self.assertIn(".plot-readout .plot-event-pinned {", styles)
        self.assertIn(".explorer-plot .plot-event-controls button {", styles)


if __name__ == "__main__":
    unittest.main()
